import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1789716686530 implements MigrationInterface {
    name = 'InitSchema1789716686530'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."account_requests_requested_role_enum" AS ENUM('DECIDEUR', 'ANALYSTE')`);
        await queryRunner.query(`CREATE TYPE "public"."account_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "account_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "full_name" character varying(150) NOT NULL, "organization" character varying(180) NOT NULL, "position" character varying(150) NOT NULL, "requested_role" "public"."account_requests_requested_role_enum" NOT NULL, "email" character varying(180) NOT NULL, "phone" character varying(50), "justification" text NOT NULL, "status" "public"."account_requests_status_enum" NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d64de2bc3d07c4e3bba400a5561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."zone_indicators_zone_type_enum" AS ENUM('region', 'district', 'commune')`);
        await queryRunner.query(`CREATE TYPE "public"."zone_indicators_risk_level_enum" AS ENUM('FAIBLE', 'MOYEN', 'ELEVE', 'CRITIQUE')`);
        await queryRunner.query(`CREATE TABLE "zone_indicators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "zone_type" "public"."zone_indicators_zone_type_enum" NOT NULL, "zone_id" uuid NOT NULL, "zone_nom" character varying(180), "population_exposed" double precision, "area_km2" double precision, "risk_mean" double precision, "risk_max" double precision, "risk_level" "public"."zone_indicators_risk_level_enum", "raster_layer_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b6f2dffe6e6a0579b5d85f7d0f5" UNIQUE ("zone_type", "zone_id"), CONSTRAINT "PK_6becbe5dc18e470324fa882afde" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."climate_observations_source_enum" AS ENUM('NASA_POWER', 'OPENWEATHER')`);
        await queryRunner.query(`CREATE TYPE "public"."climate_observations_zone_type_enum" AS ENUM('region', 'district', 'commune')`);
        await queryRunner.query(`CREATE TABLE "climate_observations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source" "public"."climate_observations_source_enum" NOT NULL, "zone_type" "public"."climate_observations_zone_type_enum" NOT NULL, "zone_id" uuid NOT NULL, "zone_code" character varying(80), "zone_nom" character varying(180), "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "observed_date" date NOT NULL, "temperature_mean" double precision, "humidity_mean" double precision, "wind_speed_mean" double precision, "precipitation" double precision, "raw" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_63de5684661a7e7b62b7e130e30" UNIQUE ("source", "zone_type", "zone_id", "observed_date"), CONSTRAINT "PK_2fd78da7bf10f9e1ecf3c02c798" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a448cd9fb04787bf5fcbde5b1f" ON "climate_observations"  ("zone_type", "zone_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1cb7c5137bcfd4d56e80a5449c" ON "climate_observations"  ("source", "observed_date") `);
        await queryRunner.query(`CREATE TYPE "public"."data_sources_code_enum" AS ENUM('CHIRPS', 'COPERNICUS_DEM', 'WORLDPOP', 'ESA_WORLDCOVER', 'HYDRORIVERS', 'OPENWEATHER', 'NASA_POWER', 'IBTRACS')`);
        await queryRunner.query(`CREATE TYPE "public"."data_sources_category_enum" AS ENUM('CLIMATE', 'TOPOGRAPHY', 'POPULATION', 'LANDCOVER', 'HYDROLOGY', 'WEATHER', 'CYCLONE')`);
        await queryRunner.query(`CREATE TYPE "public"."data_sources_status_enum" AS ENUM('CONNECTED', 'PENDING', 'FAILED', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "data_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" "public"."data_sources_code_enum" NOT NULL, "name" character varying(160) NOT NULL, "category" "public"."data_sources_category_enum" NOT NULL, "provider" character varying(160), "description" text, "url" text, "status" "public"."data_sources_status_enum" NOT NULL DEFAULT 'PENDING', "last_sync_at" TIMESTAMP, "last_success_at" TIMESTAMP, "last_error_at" TIMESTAMP, "last_error_message" text, "metadata" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8c6e8f296c781f3a835dc413431" UNIQUE ("code"), CONSTRAINT "PK_dc70b1c6b641726739857fd938d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."alertes_type_enum" AS ENUM('RISQUE_GLOBAL', 'INONDATION', 'CYCLONE', 'SECHERESSE', 'GLISSEMENT_TERRAIN', 'VENT_VIOLENT')`);
        await queryRunner.query(`CREATE TYPE "public"."alertes_niveau_enum" AS ENUM('FAIBLE', 'MOYEN', 'ELEVE', 'CRITIQUE')`);
        await queryRunner.query(`CREATE TYPE "public"."alertes_status_enum" AS ENUM('ACTIVE', 'RESOLUE', 'IGNOREE')`);
        await queryRunner.query(`CREATE TABLE "alertes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."alertes_type_enum" NOT NULL DEFAULT 'RISQUE_GLOBAL', "niveau" "public"."alertes_niveau_enum" NOT NULL, "titre" character varying(180) NOT NULL, "message" text NOT NULL, "zone_type" character varying(50), "zone_id" uuid, "zone_nom" character varying(180), "risk_value" double precision, "risk_mean" double precision, "population_exposed" double precision, "status" "public"."alertes_status_enum" NOT NULL DEFAULT 'ACTIVE', "resolved_at" TIMESTAMP WITH TIME ZONE, "gdacs_event_id" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d3116ac657eee9b912be4fd63ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a55dd1ea024b5ea681456e2d34" ON "alertes"  ("gdacs_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_20cbb804fc0f6d0b2731f0e84f" ON "alertes"  ("zone_type", "zone_id", "type", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."etl_pipeline_jobs_type_enum" AS ENUM('RISK_PIPELINE')`);
        await queryRunner.query(`CREATE TYPE "public"."etl_pipeline_jobs_status_enum" AS ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "etl_pipeline_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."etl_pipeline_jobs_type_enum" NOT NULL DEFAULT 'RISK_PIPELINE', "status" "public"."etl_pipeline_jobs_status_enum" NOT NULL DEFAULT 'PENDING', "message" text, "steps" jsonb, "alert_warning" text, "error" text, "started_at" TIMESTAMP, "finished_at" TIMESTAMP, "duration_ms" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dbc601504a9785a8d1d32dabfeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "regions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "nom" character varying(150) NOT NULL, "geom" geometry(MultiPolygon,4326), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4f6dc5a464961e7c65a395ea4c6" UNIQUE ("code"), CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "districts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "nom" character varying(150) NOT NULL, "geom" geometry(MultiPolygon,4326), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "region_id" uuid, CONSTRAINT "UQ_8e9d73424149b43b38244f75528" UNIQUE ("code"), CONSTRAINT "PK_972a72ff4e3bea5c7f43a2b98af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "communes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "nom" character varying(150) NOT NULL, "geom" geometry(MultiPolygon,4326), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "district_id" uuid, CONSTRAINT "UQ_b3f497044892b8d98c492f4900e" UNIQUE ("code"), CONSTRAINT "PK_53a9285bb669dd2298c4de525bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "active_cyclones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "gdacs_event_id" character varying(100) NOT NULL, "gdacs_episode_id" character varying(100), "name" character varying(255) NOT NULL, "latitude" double precision, "longitude" double precision, "wind_speed" character varying(100), "severity_level" character varying(100) NOT NULL, "country" character varying(150), "from_date" TIMESTAMP WITH TIME ZONE, "to_date" TIMESTAMP WITH TIME ZONE, "track_geojson" jsonb, "is_active" boolean NOT NULL DEFAULT true, "fetched_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e45f4827a58000daeb184c9352d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2adddd11fa7c520d5fb36ef393" ON "active_cyclones"  ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_732e3c809f5692da3e119f0484" ON "active_cyclones"  ("gdacs_event_id", "gdacs_episode_id") `);
        await queryRunner.query(`CREATE TABLE "weather_observations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source" character varying(80) NOT NULL DEFAULT 'OPENWEATHER', "zone_type" character varying(50), "zone_id" uuid, "zone_nom" character varying(180), "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "temperature" double precision, "humidity" double precision, "wind_speed" double precision, "wind_gust" double precision, "pressure" double precision, "rainfall" double precision, "rain_1h" double precision, "rain_3h" double precision, "clouds" double precision, "weather_main" character varying(100), "weather_description" character varying(180), "observed_at" TIMESTAMP WITH TIME ZONE NOT NULL, "raw" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b782091d02212644487558b7b8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_533865f7a6a86d96f4288a1d76" ON "weather_observations"  ("zone_type", "zone_id", "observed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f12521b7c0f358521c8df131fa" ON "weather_observations"  ("source", "observed_at") `);
        await queryRunner.query(`CREATE TYPE "public"."operational_risk_signals_risk_type_enum" AS ENUM('FLOOD', 'DROUGHT', 'LANDSLIDE', 'CYCLONE')`);
        await queryRunner.query(`CREATE TYPE "public"."operational_risk_signals_signal_level_enum" AS ENUM('FAIBLE', 'MOYEN', 'ELEVE', 'CRITIQUE')`);
        await queryRunner.query(`CREATE TABLE "operational_risk_signals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "risk_type" "public"."operational_risk_signals_risk_type_enum" NOT NULL, "zone_type" character varying(50) NOT NULL, "zone_id" uuid NOT NULL, "zone_nom" character varying(180) NOT NULL, "background_risk_max" double precision, "background_risk_mean" double precision, "weather_factor" double precision, "signal_score" double precision NOT NULL, "signal_level" "public"."operational_risk_signals_signal_level_enum" NOT NULL, "message" text NOT NULL, "observed_at" TIMESTAMP WITH TIME ZONE, "details" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1c1d417c628c5e9361cdda48594" UNIQUE ("risk_type", "zone_type", "zone_id"), CONSTRAINT "PK_a0b0855200675d93ef773d7fb95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_488bfa51a5f70aee53e61b2565" ON "operational_risk_signals"  ("signal_level") `);
        await queryRunner.query(`CREATE INDEX "IDX_2da7bf1f7d3397f255fae00632" ON "operational_risk_signals"  ("risk_type", "zone_type") `);
        await queryRunner.query(`CREATE TYPE "public"."raster_layers_type_enum" AS ENUM('RAINFALL', 'SLOPE', 'POPULATION', 'LANDCOVER', 'RISK_INDEX', 'RISK_CLASSIFIED', 'FLOOD_HAZARD_INDEX', 'FLOOD_RISK_INDEX', 'FLOOD_RISK_CLASSIFIED', 'DROUGHT_HAZARD_INDEX', 'DROUGHT_RISK_INDEX', 'DROUGHT_RISK_CLASSIFIED', 'LANDSLIDE_HAZARD_INDEX', 'LANDSLIDE_RISK_INDEX', 'LANDSLIDE_RISK_CLASSIFIED', 'CYCLONE_HAZARD_INDEX', 'CYCLONE_RISK_INDEX', 'CYCLONE_RISK_CLASSIFIED', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "raster_layers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "type" "public"."raster_layers_type_enum" NOT NULL DEFAULT 'OTHER', "file_path" text NOT NULL, "description" text, "crs" character varying(80), "resolution_x" double precision, "resolution_y" double precision, "min_value" double precision, "max_value" double precision, "mean_value" double precision, "width" integer, "height" integer, "bounds" character varying(80), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3398391b711e33093267086db70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "generated_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(180) NOT NULL, "report_type" character varying(80) NOT NULL, "format" character varying(20) NOT NULL, "file_name" character varying(240) NOT NULL, "file_path" text NOT NULL, "mime_type" character varying(160) NOT NULL, "filters" jsonb, "generated_by" character varying(180), "generated_at_local" character varying(80), "version" character varying(40) NOT NULL DEFAULT '1.0', "status" character varying(40) NOT NULL DEFAULT 'GENERATED', "file_size_bytes" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3875618b27e8f2d438168399374" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."risk_criteria_weights_criterion_code_enum" AS ENUM('RAINFALL', 'SLOPE', 'POPULATION', 'LANDCOVER')`);
        await queryRunner.query(`CREATE TABLE "risk_criteria_weights" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "criterion_code" "public"."risk_criteria_weights_criterion_code_enum" NOT NULL, "label" character varying(100) NOT NULL, "weight" double precision NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5ae02b58101324e0738ddbc3ee1" UNIQUE ("criterion_code"), CONSTRAINT "PK_169d69c8fce158dc16c30c588af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."risk_model_weights_risk_type_enum" AS ENUM('FLOOD', 'DROUGHT', 'LANDSLIDE', 'CYCLONE')`);
        await queryRunner.query(`CREATE TYPE "public"."risk_model_weights_model_part_enum" AS ENUM('HAZARD', 'RISK')`);
        await queryRunner.query(`CREATE TABLE "risk_model_weights" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "risk_type" "public"."risk_model_weights_risk_type_enum" NOT NULL, "model_part" "public"."risk_model_weights_model_part_enum" NOT NULL, "criterion" character varying(120) NOT NULL, "label" character varying(180) NOT NULL, "weight" double precision NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a8918b2b876f3b0b486cc2f0c44" UNIQUE ("risk_type", "model_part", "criterion"), CONSTRAINT "PK_f8b3914f9c7cb41f84c1256f6ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_571b13ea6e2d7699720f9861cd" ON "risk_model_weights"  ("risk_type", "model_part") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "email" character varying(150) NOT NULL, "password_hash" character varying NOT NULL, "phone" character varying(30), "avatar_url" text, "is_active" boolean NOT NULL DEFAULT true, "refresh_token_hash" character varying, "password_reset_token_hash" character varying, "password_reset_expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "role_id" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."zone_risk_indicators_risk_type_enum" AS ENUM('GLOBAL', 'FLOOD', 'DROUGHT', 'CYCLONE', 'LANDSLIDE', 'HEAT', 'WIND')`);
        await queryRunner.query(`CREATE TYPE "public"."zone_risk_indicators_zone_type_enum" AS ENUM('region', 'district', 'commune')`);
        await queryRunner.query(`CREATE TYPE "public"."zone_risk_indicators_risk_level_enum" AS ENUM('FAIBLE', 'MOYEN', 'ELEVE', 'CRITIQUE')`);
        await queryRunner.query(`CREATE TABLE "zone_risk_indicators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "risk_type" "public"."zone_risk_indicators_risk_type_enum" NOT NULL, "zone_type" "public"."zone_risk_indicators_zone_type_enum" NOT NULL, "zone_id" uuid NOT NULL, "zone_code" character varying(80), "zone_nom" character varying(180), "risk_mean" double precision, "risk_max" double precision, "hazard_mean" double precision, "population_exposed" double precision, "area_km2" double precision, "risk_level" "public"."zone_risk_indicators_risk_level_enum", "raster_layer_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_68b0ec725d890377aaca07e11fc" UNIQUE ("risk_type", "zone_type", "zone_id"), CONSTRAINT "PK_2ef34df2b93528cd0eee6000646" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_04ecd633a1a55a89005f3a1100" ON "zone_risk_indicators"  ("risk_type", "risk_max") `);
        await queryRunner.query(`CREATE INDEX "IDX_d99b7d0d9329d977ca71c394e5" ON "zone_risk_indicators"  ("risk_type", "zone_type") `);
        await queryRunner.query(`ALTER TABLE "districts" ADD CONSTRAINT "FK_4271e8e205bbdce31975c55ed3f" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communes" ADD CONSTRAINT "FK_3e59bae49f401b78b66b8ae4d2f" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "communes" DROP CONSTRAINT "FK_3e59bae49f401b78b66b8ae4d2f"`);
        await queryRunner.query(`ALTER TABLE "districts" DROP CONSTRAINT "FK_4271e8e205bbdce31975c55ed3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d99b7d0d9329d977ca71c394e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04ecd633a1a55a89005f3a1100"`);
        await queryRunner.query(`DROP TABLE "zone_risk_indicators"`);
        await queryRunner.query(`DROP TYPE "public"."zone_risk_indicators_risk_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."zone_risk_indicators_zone_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."zone_risk_indicators_risk_type_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_571b13ea6e2d7699720f9861cd"`);
        await queryRunner.query(`DROP TABLE "risk_model_weights"`);
        await queryRunner.query(`DROP TYPE "public"."risk_model_weights_model_part_enum"`);
        await queryRunner.query(`DROP TYPE "public"."risk_model_weights_risk_type_enum"`);
        await queryRunner.query(`DROP TABLE "risk_criteria_weights"`);
        await queryRunner.query(`DROP TYPE "public"."risk_criteria_weights_criterion_code_enum"`);
        await queryRunner.query(`DROP TABLE "generated_reports"`);
        await queryRunner.query(`DROP TABLE "raster_layers"`);
        await queryRunner.query(`DROP TYPE "public"."raster_layers_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2da7bf1f7d3397f255fae00632"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_488bfa51a5f70aee53e61b2565"`);
        await queryRunner.query(`DROP TABLE "operational_risk_signals"`);
        await queryRunner.query(`DROP TYPE "public"."operational_risk_signals_signal_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."operational_risk_signals_risk_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f12521b7c0f358521c8df131fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_533865f7a6a86d96f4288a1d76"`);
        await queryRunner.query(`DROP TABLE "weather_observations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_732e3c809f5692da3e119f0484"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2adddd11fa7c520d5fb36ef393"`);
        await queryRunner.query(`DROP TABLE "active_cyclones"`);
        await queryRunner.query(`DROP TABLE "communes"`);
        await queryRunner.query(`DROP TABLE "districts"`);
        await queryRunner.query(`DROP TABLE "regions"`);
        await queryRunner.query(`DROP TABLE "etl_pipeline_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."etl_pipeline_jobs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."etl_pipeline_jobs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20cbb804fc0f6d0b2731f0e84f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a55dd1ea024b5ea681456e2d34"`);
        await queryRunner.query(`DROP TABLE "alertes"`);
        await queryRunner.query(`DROP TYPE "public"."alertes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alertes_niveau_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alertes_type_enum"`);
        await queryRunner.query(`DROP TABLE "data_sources"`);
        await queryRunner.query(`DROP TYPE "public"."data_sources_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."data_sources_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."data_sources_code_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cb7c5137bcfd4d56e80a5449c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a448cd9fb04787bf5fcbde5b1f"`);
        await queryRunner.query(`DROP TABLE "climate_observations"`);
        await queryRunner.query(`DROP TYPE "public"."climate_observations_zone_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."climate_observations_source_enum"`);
        await queryRunner.query(`DROP TABLE "zone_indicators"`);
        await queryRunner.query(`DROP TYPE "public"."zone_indicators_risk_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."zone_indicators_zone_type_enum"`);
        await queryRunner.query(`DROP TABLE "account_requests"`);
        await queryRunner.query(`DROP TYPE "public"."account_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."account_requests_requested_role_enum"`);
    }

}
